create table if not exists public.stock (
  stock_code text primary key,
  description text not null default '',
  quantity numeric not null default 0,
  target_level numeric not null default 0,
  stock_group text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  po_number text not null,
  stock_code text not null,
  description text not null default '',
  supplier text not null default '',
  order_date date,
  due_date date,
  quantity_outstanding numeric not null default 0,
  updated_at timestamptz not null default now(),
  unique (po_number, stock_code)
);

alter table public.stock enable row level security;
alter table public.purchase_orders enable row level security;

create policy "authenticated users can read stock"
  on public.stock for select
  to authenticated
  using (true);

create policy "authenticated users can insert stock"
  on public.stock for insert
  to authenticated
  with check (true);

create policy "authenticated users can update stock"
  on public.stock for update
  to authenticated
  using (true)
  with check (true);

create policy "authenticated users can delete stock"
  on public.stock for delete
  to authenticated
  using (true);

create policy "authenticated users can read purchase orders"
  on public.purchase_orders for select
  to authenticated
  using (true);

create policy "authenticated users can insert purchase orders"
  on public.purchase_orders for insert
  to authenticated
  with check (true);

create policy "authenticated users can update purchase orders"
  on public.purchase_orders for update
  to authenticated
  using (true)
  with check (true);

create policy "authenticated users can delete purchase orders"
  on public.purchase_orders for delete
  to authenticated
  using (true);

create index if not exists purchase_orders_stock_code_idx
  on public.purchase_orders(stock_code);

create index if not exists purchase_orders_due_date_idx
  on public.purchase_orders(due_date);
