create extension if not exists pgcrypto;

drop table if exists public.purchase_orders cascade;
drop table if exists public.stock cascade;
drop table if exists public.memberships cascade;
drop table if exists public.organizations cascade;

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.memberships (
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'manager', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (org_id, user_id)
);

create table public.stock (
  org_id uuid not null references public.organizations(id) on delete cascade,
  stock_code text not null,
  description text not null default '',
  quantity numeric not null default 0,
  target_level numeric not null default 0,
  stock_group text not null default '',
  updated_at timestamptz not null default now(),
  primary key (org_id, stock_code)
);

create table public.purchase_orders (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  po_number text not null,
  stock_code text not null,
  description text not null default '',
  supplier text not null default '',
  order_date date,
  due_date date,
  quantity_outstanding numeric not null default 0,
  updated_at timestamptz not null default now(),
  unique (org_id, po_number, stock_code)
);

create or replace function public.user_has_org_access(target_org uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.memberships
    where org_id = target_org and user_id = auth.uid()
  );
$$;

create or replace function public.user_is_org_admin(target_org uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.memberships
    where org_id = target_org and user_id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.create_initial_organization(org_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_org_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if exists (select 1 from public.organizations) then
    raise exception 'Initial organisation has already been created';
  end if;

  insert into public.organizations(name) values (trim(org_name))
  returning id into new_org_id;

  insert into public.memberships(org_id, user_id, role)
  values (new_org_id, auth.uid(), 'admin');

  return new_org_id;
end;
$$;

alter table public.organizations enable row level security;
alter table public.memberships enable row level security;
alter table public.stock enable row level security;
alter table public.purchase_orders enable row level security;

create policy "members can read their organisation"
  on public.organizations for select to authenticated
  using (public.user_has_org_access(id));

create policy "users can read their own membership"
  on public.memberships for select to authenticated
  using (user_id = auth.uid() or public.user_is_org_admin(org_id));

create policy "members can read stock"
  on public.stock for select to authenticated
  using (public.user_has_org_access(org_id));

create policy "managers can insert stock"
  on public.stock for insert to authenticated
  with check (public.user_is_org_admin(org_id) or exists (
    select 1 from public.memberships
    where org_id = stock.org_id and user_id = auth.uid() and role = 'manager'
  ));

create policy "managers can update stock"
  on public.stock for update to authenticated
  using (public.user_is_org_admin(org_id) or exists (
    select 1 from public.memberships
    where org_id = stock.org_id and user_id = auth.uid() and role = 'manager'
  ))
  with check (public.user_has_org_access(org_id));

create policy "admins can delete stock"
  on public.stock for delete to authenticated
  using (public.user_is_org_admin(org_id));

create policy "members can read purchase orders"
  on public.purchase_orders for select to authenticated
  using (public.user_has_org_access(org_id));

create policy "managers can insert purchase orders"
  on public.purchase_orders for insert to authenticated
  with check (public.user_is_org_admin(org_id) or exists (
    select 1 from public.memberships
    where org_id = purchase_orders.org_id and user_id = auth.uid() and role = 'manager'
  ));

create policy "managers can update purchase orders"
  on public.purchase_orders for update to authenticated
  using (public.user_is_org_admin(org_id) or exists (
    select 1 from public.memberships
    where org_id = purchase_orders.org_id and user_id = auth.uid() and role = 'manager'
  ))
  with check (public.user_has_org_access(org_id));

create policy "admins can delete purchase orders"
  on public.purchase_orders for delete to authenticated
  using (public.user_is_org_admin(org_id));

create index stock_org_idx on public.stock(org_id);
create index purchase_orders_org_idx on public.purchase_orders(org_id);
create index purchase_orders_stock_code_idx on public.purchase_orders(org_id, stock_code);
create index purchase_orders_due_date_idx on public.purchase_orders(org_id, due_date);
